# Generated by Django 5.0.3 on 2024-03-22 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportreadstatus',
            old_name='is_read',
            new_name='read',
        ),
        migrations.AddField(
            model_name='report',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
