# Generated by Django 5.0.3 on 2024-03-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_is_read_reportreadstatus_read_report_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='read_by',
        ),
    ]
