# Generated by Django 5.0.3 on 2024-03-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_report_completed_by_report_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='completed_by',
        ),
    ]
